### ISSUE TITLE
Nearby is empty, and server log prints NaN errors

### ISSUE THREAD

**Issue by cheesejaguar** [zaksabeast/pokemon-go-3-step-fix#1]
Wild Pokemon  RATTATA  is  NaN m away!

For every pokemon, and I'm guessing this is what is causing the empty "Nearby" tab for me.

**Comment by zaksabeast** [comment]
Without more information, it's hard to determine what happened.
This looks very much like a database error.  Since "RATTATA" is showing, that means there is a Pokemon nearby, because that information is being pulled from the data sent to the phone directly.  The distance is created with variables from the database, but it may not getting an accurate reading.

If there aren't any database errors in the console (which would only be displayed from the CoffeeScript), then the PHP script may not have the correct database username and password.

When testing, I had the issue of Pokemon not showing up in the Nearby list when a bad distance was given, so having no Pokemon show up makes sense as well.

I'm hoping to soon get rid of the need for a database, so it will just be the CoffeeScript without PHP or a database.

**Comment by cheesejaguar** [comment]
Overlooked that the php script needed mysql credentials as well, ty
